config/routes.rb
Rails.application.routes.draw do
  root 'login#index'
  post 'login', to: 'login#login'
  get 'logout', to: 'login#logout'
  resources :tasks do
  	put 'complete'
  end

  get '/shared', to: 'sharing#shared'

  get 'users/:user_id/tasks', to: 'sharing#index'
  post 'share', to: 'sharing#share'
end

app/models/share.rb
class Share < ActiveRecord::Base
  validates :from_user_id, :to_user_id, presence: true
  belongs_to :user, foreign_key: :from_user_id
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true
  validates :user_id, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  
  validates :email, presence: true
  has_secure_password

  has_many :shares, foreign_key: 'from_user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_current_user_from_session

  def set_current_user_from_session    
    @current_user = User.find_by(id: session[:user_id])
    logger.debug "Logged in user #{@current_user.email unless @current_user.nil?}"

    if(@current_user.nil?)
      redirect_to root_url
    end
  end    
end

app/controllers/login_controller.rb
class LoginController < ActionController::Base
  protect_from_forgery with: :exception
  
  layout "login"

  before_action :set_user, only: [:login]

  def index
    # If in development mode, allow a url to log in like localhost:3000?userid=2
    if Rails.env.development? && !params[:userid].nil?
      session[:user_id] = params[:userid]
      redirect_to tasks_url
    end    
  end

  def login
    respond_to do |format|
      if @user && @user.authenticate(login_params[:password])
        session[:user_id] = @user.id
        format.html { redirect_to tasks_url, notice: 'Logged in successfully.' }
      else
        format.html { redirect_to root_url, notice: 'Credentials were invalid.' }
      end
    end    
  end

  def logout
    respond_to do |format|
      session[:user_id] = nil
      reset_session
      format.html { redirect_to root_url, notice: 'Logged out successfully.' }
    end      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(email: login_params[:email])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.permit(:email, :password)
    end
end

app/controllers/sharing_controller.rb
class SharingController < ApplicationController
  def index
    if(Share.exists?(from_user_id: params[:user_id], to_user_id: @current_user.id))
      @tasks = Task.where(user_id: params[:user_id])
    else
      redirect_to tasks_url
    end
  end

  def share
    @share = Share.new
  	@share.from_user_id = @current_user.id
  	@share.to_user_id = share_params[:id]
  	respond_to do |format|
	  if @share.save
	    format.html { redirect_to tasks_url, notice: 'Task list has been shared successfully.' }
	  else
	    format.html { redirect_to tasks_url, notice: 'Task list share was unsuccessful'}
	  end
    end
  end

  def shared
  	@shared = Share.includes(:user).where(to_user_id: @current_user.id)
  end

  private

    # Whitelist parameters and set the user association
    def share_params
      params.require(:share).permit(:id)
    end    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:update, :destroy]
  before_action :set_tasks, only: [:index, :create]
  before_action :set_new_task, only: [:index]
  before_action :set_users, only: [:index]

  def index
    @share = Share.new
  end

  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
      else
        format.html { redirect_to tasks_url}
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
      else
        format.html { redirect_to tasks_url, notice: 'Task could not be updated.' }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully deleted.' }
    end
  end

  def complete
    @task = Task.find(params[:task_id])
    @task.completed = true
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was completed successfully.' }
      else
        format.html { redirect_to tasks_url, notice: 'Task could not be completed.' }
      end
    end
  end

  private

    def set_users
      @users = User.where.not(id: @current_user.id)
    end
    
    def set_task
      @task = Task.find(params[:id])
    end

    def set_new_task
      @task = Task.new
    end

    def set_tasks
      @tasks = Task.where(user_id: @current_user.id)
    end

    # Whitelist parameters and set the user association
    def task_params
      params.require(:task).permit(:name).merge(user_id: @current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tasks_active?
  	params[:controller] == 'tasks'
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monkey Tasks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="fixed">
	<nav class="top-bar" data-topbar role="navigation">
	  <ul class="title-area">
	    <li class="name">
	      <h1><a href="/tasks">Monkey Tasks</a></h1>
	    </li>
	  </ul>

	  <section class="top-bar-section">
	    <ul class="left">
	        <li class="<%= 'active' if tasks_active? %>"><a href="/tasks">Tasks</a></li>
	        <li class="<%= 'active' if !tasks_active? %>"><a href="/shared">Shared</a></li>
	    </ul>
	    <ul class="right">
	    	<li><a href="/logout">Log Out</a></li>
	    </ul>
	  </section>
	</nav>	
</div>	
<div class="main-content">
	<%= yield %>
</div>
<footer>
	<h4>Monkey Tasks</h4>
</footer>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monkey Tasks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="fixed">
	<nav class="top-bar" data-topbar role="navigation">
	  <ul class="title-area">
	    <li class="name">
	      <h1><a href="/">Monkey Tasks</a></h1>
	    </li>
	  </ul>
	</nav>	
</div>	
<div class="main-content">
	<%= yield %>
</div>
<footer>
	<h4>Monkey Tasks</h4>
</footer>
</body>
</html>

app/views/login/index.html.erb
<div class="panel login-panel">	
	<%= form_tag('/login') do %>
	    <% if flash[:notice] %>
			<div class="row">
				<div data-alert class="alert-box <%=flash[:notice].include?('invalid') ? 'alert' : 'success' %>">
					<%= flash[:notice] %>
					<a href="#" class="close">&times;</a>
				</div>
			</div>
		<% end %>
		<div class="row">
			<div class="small-2 columns">
				<%= label_tag 'email', 'Email', class:'right inline' %>
			</div>
			<div class="small-10 columns">
		      <%= text_field_tag :email %>
		  	</div>
  		</div>
  		<div class="row">
		  	<div class="small-2 columns">
		  		<%= label_tag 'password', 'Password', class:'right inline' %>
		  	</div>
		  	<div class="small-10 columns">
		      <%= password_field_tag :password %>
		  	</div>
	  	</div>
	  	<div class="row">
	  		<div class="right">
      			<%= submit_tag 'Login', class: 'button success login-button' %>
      		</div>
      	</div>
	<% end %>
</panel>

app/views/sharing/index.html.erb
<div class="panel">
  <div class="row">
    <table>
      <thead>
        <tr>
          <th>Task</th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td>
              <% if task.completed %>
                <span class="strike"><%= task.name %></span>
              <% else %>
                <%= task.name %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>  	
  </div>
</div>

app/views/sharing/shared.html.erb
<div class="panel">
  <div class="row">
    <table>
      <thead>
        <tr>
          <th>Shared Task Lists</th>
        </tr>
      </thead>
      <tbody>
        <% @shared.each do |share| %>
          <tr>
            <td>
            	<%= link_to share.user.email,"/users/#{share.from_user_id}/tasks" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>  	
  </div>
</div>

app/views/tasks/index.html.erb
<div class="panel">
  <div class="row">
    <%= form_for(@task) do |f| %>
      <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.text_field :name %>
      <%= f.submit 'Add', class: 'button success' %>
    <% end %>
  </div>
  <div class="row">
    <table>
      <thead>
        <tr>
          <th width="5%">Complete</th>
          <th>Task</th>
          <th width="5%">Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td class="action">
              <%= link_to raw('<i class="fa fa-check-circle-o fa-lg"></i>'), task_complete_path(task), method: :put %>
            </td>
            <td>
              <% if task.completed %>
                <%= link_to task.name, '#', class:'strike', :data => { 'reveal-id' => "task-modal-#{task.id}" } %>
              <% else %>
                <%= link_to task.name, '#', :data => { 'reveal-id' => "task-modal-#{task.id}" } %>
              <% end %>
              <div id="task-modal-<%=task.id %>" class="reveal-modal" data-reveal role="dialog">
                <h2>Edit Task</h2>
                <%= form_for(task) do |task_form| %>
                    <%= task_form.text_field :name %>
                    <%= task_form.submit 'Save', class: 'button success' %>
                <% end %>
                <a class="close-reveal-modal" aria-label="Close">&#215;</a>
              </div>              
            </td>
            <td class="action">
              <%= link_to raw('<i class="fa fa-trash fa-lg"></i>'), task, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="share">
      <%= form_for(@share, url: '/share', method: :post) do |f| %>
        <%= f.collection_select(:id, @users, :id, :email, { :prompt => 'Select a User' }, class: 'user-list') %>
        <%= f.submit 'Share', class: 'button success' %>
      <% end %>
    </div>
  </div>
</div>